DROP TABLE "ATG_3163_ADDL_FIELDS";

CREATE TABLE "ATG_3163_ADDL_FIELDS"(
 "PART" CHAR(20) NOT NULL ,
 "LOC" CHAR(2) NOT NULL ,
 "SERVICE_PART" BIT NOT NULL ,
 "CONSIGNMENT" BIT NOT NULL ,
 "KANBAN" BIT NOT NULL ,
 "GL_ACCOUNT" CHAR(15) NOT NULL ,
 "FIRST_SHIPPED_DATE" DATETIME NOT NULL ,
 "CUSTOMER" CHAR(6) NOT NULL ,
 "USER_1" DATETIME NOT NULL ,
 "USER_2" DATETIME NOT NULL ,
 "USER_3" DATETIME NOT NULL ,
 "USER_4" DATETIME NOT NULL ,
 "USER_5" DOUBLE NOT NULL ,
 "USER_6" DOUBLE NOT NULL ,
 "USER_7" DOUBLE NOT NULL ,
 "USER_8" DOUBLE NOT NULL ,
 "USER_9" DOUBLE NOT NULL ,
 "USER_10" CHAR(50) NOT NULL ,
 "USER_11" CHAR(50) NOT NULL ,
 "USER_12" CHAR(50) NOT NULL ,
 "USER_13" CHAR(50) NOT NULL ,
 "USER_14" CHAR(50) NOT NULL ,
 "USER_15" CHAR(50) NOT NULL ,
 PRIMARY KEY ("PART", "LOC")
);

